name: Tests

on:
  push:
    branches: [ 0.x ]
  pull_request:
    branches: [ 0.x ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0']
        
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ matrix-php }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ matrix.php }}-composer-
          
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        extensions: "json,sodium"
        php-version: "${{ matrix.php }}"
        
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
 
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run tests
      run: vendor/bin/phpunit -v
      
    # - name: Run test suite
    #   run: composer run-script test
